socialsimple/accounts/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth.views import LoginView,LogoutView
from . import views


app_name = 'accounts'

urlpatterns = [
    # default is registration/login.html
    #url(r'^login/$', auth_views.login, name='login'),
    path('login', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('accounts/logout',LogoutView.as_view(template_name='accounts/index.html'), name='logout',kwargs={'next_page':'/'}),
    path('logout', LogoutView.as_view(), name='logout'),
    # by default go back to  homepage
    path('', include('django.contrib.auth.urls')), #Q: login not work unless put this line in the same file with login

    # creation sign up page
    path('signup', views.SignUp.as_view(), name='signup'),
]

socialsimple/groups/urls.py
from django.urls import include,path
from . import views


app_name = 'groups'

urlpatterns = [
    path('grouplist', views.GroupListView.as_view(), name='group-list'),
    path('groupcreate', views.GroupCreate.as_view(), name='groupcreate'),
    path('groupdetail/<slug>', views.GroupViewDetails.as_view(), name='groupdetail'),
    path('joingroup', views.JoinGroup.as_view(), name='join'),
    path('leavegroup', views.LeaveGroup.as_view(), name='leave'),

    ]

socialsimple/posts/urls.py
from django.urls import include,path

from . import views


app_name = 'posts'

urlpatterns = [
    path('listpost', views.ListPost.as_view(), name='listpost'),
    path('postdetail/<username>/<pk>', views.PostDetail.as_view(), name='details'),
    path('createpost', views.CreatePost.as_view(), name='createpost'),



]

socialsimple/socialsimple/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'), # new



]

socialsimple/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

# Create your models here.
class CustomUser(AbstractUser):

    date_of_birth = models.DateField(max_length=140, blank=True, null=True)

    def __str__(self):
        return self.email

socialsimple/groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
import misaka as m
from django.utils.text import slugify
from django.urls import reverse
from django import  template

#register = template.Library()

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=255,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)

    members = models.ManyToManyField(User,through='GroupMember')

    def __str__ (self):
        return self.name

    def save (self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description = m.html(self.description)
        print(f'----------group description_html is {self.description}-------')
        super().save(args,kwargs)

    def get_absolute_url(self):
        # F: question
        return reverse('groups:groupdetail',kwargs={'slug':self.slug})
        # return reverse('groups:groupdetail', kwargs={'pk': self.pk})


    class Meta:
        ordering =['-name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships', on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together=['group','user']

socialsimple/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
import misaka as m
from django.utils.text import slugify
from django.urls import reverse
from groups.models import Group
# Create your models here.

class Post(models.Model):

    user = models.ForeignKey(User, related_name = 'posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)

    group = models.ForeignKey(Group, related_name = 'posts',null=True, blank=True,on_delete=models.DO_NOTHING)


    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        message = m.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:details', kwargs={'username':self.user.username,'pk':self.pk })

    class Meta:

        ordering = ['-created_at']
        unique_together = ['user','message']

socialsimple/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields =('username','email','date_of_birth')



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields =('username','email','date_of_birth')

socialsimple/groups/forms.py
from django import forms
from posts.models import Post
from groups.models import Group

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('name','description')

socialsimple/posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):


    class Meta:
        model =  Post
        fields = ('message','group')

socialsimple/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

class SignUp(generic.CreateView):

    form_class = CustomUserCreationForm
    success_url = reverse_lazy('home')
    template_name='accounts/signup.html'

socialsimple/groups/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
CreateView,UpdateView,DeleteView)
# Create your views here.
from . models import Group
from django.utils import timezone
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin

class GroupList(ListView):
    model = Group
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class GroupCreate(LoginRequiredMixin,CreateView):
    model = Group
    fields = ['name','description']
    # this is the default form
    # form_class = GroupForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        print(f'user is {form.instance.user.username}')
        return super().form_valid(form)

class GroupViewDetails(DetailView):
    model = Group

class GroupListView(ListView):
    model = Group

class GroupUpdate(UpdateView):
    pass
class GroupDelete(DeleteView):
    model = Group

class JoinGroup(TemplateView):
    pass
class LeaveGroup(TemplateView):
    pass

socialsimple/posts/views.py
#### posts.view ####
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
CreateView,UpdateView,DeleteView)
# Create your views here.
from . models import Post
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from . forms import PostForm
from django.urls import reverse_lazy

class ListPost(ListView):
    model = Post
    #default template post_list.html
    def get_queryset(self):
        return Post.objects.filter(created_at__lte=timezone.now()).order_by('-created_at')

class PostDetail(DetailView):
    model = Post

class CreatePost(LoginRequiredMixin,CreateView):
    # login_url=
        redirect_field_name ='post_detail.html'
        model = Post
    # either use default post_form.html or set template name specify path
    #    template_name = 'posts/post_form.html'

        form_class = PostForm
        # success_url = reverse_lazy('listpost')

        def form_valid(self, form):

            form.instance.user = self.request.user
            return super().form_valid(form)

socialsimple/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

socialsimple/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<p>Sign Up</p>
<div class="jumbotron">


<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
  {% endblock %}
</div>

socialsimple/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

<div class = "row">

  {% block pregroup %} {% endblock %}
  {% block groupcontent %} {% endblock %}
  {% block postgroup %} {% endblock %}

  </div>

</div>

{% endblock %}

socialsimple/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}



<div class="content">

  <h1>{{group.name}}</h1>
  <h2>Member count: {{ group.members.count }}</h2>

  {% if not user in group.members.all %}
  <a href="{% url 'groups:join' %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>

  {% else %}
  <a href="{% url 'groups:leave' %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Leave</a>
  {% endif %}

</div>

{% endblock %}

socialsimple/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% block content %}

<form method="post">

  {% csrf_token %}
  {{ form.as_p }}
  <input type="Submit" class="btn btn-primary" value="Submit">

{% endblock %}

socialsimple/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}


{% block pregroup %}
  <h2>Group List Page</h2>
<div class="content">

  {% if user.is_authenticated %}
  <h2>Wecome back, {{ user.username}}</h2>


  {% for group in object_list%}

<p>Group Name: <a href="{% url 'groups:groupdetail' slug=group.slug %}">{{ group.name }}</a> </p>
<p>Group Description: {{ group.description_html|safe }}</p>
<p>Group member counts: {{ group.members.count|pluralize }}</p>
<p>Group post counts!: {{ group.posts.count|pluralize }}</p>

    {% empty %}
   there are no groups availabe

  {% endfor %}

{% endif %}
</div>

{% endblock %}

socialsimple/posts/templates/posts/post_detail.html
{% extends 'base.html' %}
View Post Details

{% block content %}

<div class="content">
<p> Post Message: {{ post.message }} </p>
<p> created by: {{ post.user.username}}</p>
<p> create date: {{ post.created_at}}</p>

  
</div>
{% endblock %}

socialsimple/posts/templates/posts/post_form.html
{% extends 'base.html' %}



{% block content %}

<form method="post">

  {% csrf_token %}
  {{ form.as_p }}
  <input type="Submit" class="btn btn-primary" value="Submit">
  
{% endblock %}

socialsimple/posts/templates/posts/post_list.html
{% extends 'base.html' %}



{% block content %}

  <h2>Post List Page</h2>


  {% for post in object_list%}

<p> <h1><a href="{% url 'posts:details' username=post.user.username pk=post.pk %}">{{ post.message }}</a></h1></p>
<p>Create Date: {{ post.created_at }} </p>

    {% empty %}
   there are no posts availabe

  {% endfor %}

{% endblock %}

socialsimple/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

{# MEDIUM STYLE EDITOR#}
  <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


  {# Custom CSS#}
  <link rel="stylesheet" href="{% static 'socialsimple/css/master.css' %}">

  {# Fonts#}
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
  <meta charset="utf-8">
  <title></title>
</head>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Felix Social Blog Assignment</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>

          <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     Post
   </a>
   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
     <a class="dropdown-item" href="{% url 'posts:listpost' %}">List Post</a>
     <a class="dropdown-item" href="{% url 'posts:createpost' %}">Create Post</a>
     <div class="dropdown-divider"></div>
     <a class="dropdown-item" href="#">Something else here</a>
   </div>
 </li>


        <li><a href="#">Group</a></li>
          <li>  <a href="{% url 'groups:group-list' %}">List Group</a></li>
          <li>  <a href="{% url 'groups:groupcreate' %}">Create New Group</a></li>
        <li>  <a href="{% url 'posts:listpost' %}">List Post</a></li>
        <li>  <a href="{% url 'posts:createpost' %}">Create Post</a></li>
          {%  if not user.is_authenticated %}
          <li><a href="{% url 'accounts:login' %}">login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>


              {% else %}
                <li><a href="{% url 'accounts:logout' %}">logout</a>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}

  </body>
</html>

socialsimple/templates/index.html
{% extends 'base.html' %}


{% block content %}


<div class="jumbotron">
<p>Welcome to home page</p>

{% if user.is_authenticated %}
  Hi {{ user.username }}!
  welcome to home page
<a href="{% url 'accounts:logout' %}">logout</a>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'accounts:login' %}">login</a>
</div>
{% endif %}
{% endblock %}